# Generated by Django 5.0.6 on 2024-05-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyname", models.CharField(max_length=50)),
                ("e_mail", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("e_mail", models.CharField(max_length=50)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ContactusCom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("e_mail", models.CharField(max_length=50)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ContactusUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("e_mail", models.CharField(max_length=50)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_mail", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SearchEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.CharField(max_length=75)),
                ("e_mail", models.CharField(max_length=50)),
                ("languages", models.CharField(max_length=50)),
                ("degree", models.CharField(max_length=50)),
                ("experience", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("e_mail", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
                ("filepdf", models.FileField(upload_to="files/")),
            ],
        ),
    ]
