# Generated by Django 5.0.6 on 2024-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_user_filepdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="filepdf",
            field=models.FileField(upload_to="media/"),
        ),
    ]
