# Generated by Django 5.0.6 on 2024-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rate",
            field=models.IntegerField(default=0),
        ),
    ]
